affairs/admin/routes.py
from flask import Flask, render_template, redirect, url_for, Blueprint, request, jsonify
from flask.globals import request  
from affairs.admin.forms import Admin, KategoriF, LoginA, ArtikelP, editArtikel, UploadCSv
from affairs import db, app,bcrypt
from affairs.models import admindb, Kategori, Artikel, CustomerPgAir
from flask_login import login_user, logout_user, current_user, login_required 
import os
import csv
import secrets
import json

admingam = Blueprint('admingam', __name__)

def gthumbnail(file_foto):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(file_foto.filename)
    nama_gambar = random_hex + f_ext
    file_foto.save(os.path.join(app.root_path, 'affairs/static/img', nama_gambar))
    return nama_gambar
    
def savecsv(file_csv):
    data = []
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(file_csv.filename)
    nama_csv = random_hex + f_ext
    file_csv.save(os.path.join(app.root_path, 'affairs/static/csv', nama_csv))
    
    with open('affairs/static/csv/' + nama_csv) as file:
        csvfile = csv.DictReader(file)
        for row in csvfile:
          data.append(row)
        return data
        
    

@admingam.route("/")
def home():
    halaman = request.args.get('page',1, type=int)
    daf_ar = Artikel.query.order_by(Artikel.id.desc()).paginate(page=halaman, per_page=3)
    return render_template("index.html", daf_ar=daf_ar)

@admingam.route('/baca_ar/<int:id>')
def baca_ar(id):
    bca = Artikel.query.get_or_404(id)
    return render_template('baca_ar.html', bca=bca)

@admingam.route("/about")
def about():
    return render_template("about.html")

@admingam.route("/contact")
def contact():
    return render_template("contact.html")
 
@admingam.route("/post")
def post():
    return render_template("post.html")
#risno456

@admingam.route("/admin-daftar-akun", methods=["GET","POST"])
def admin():
    form = Admin()
    if form.validate_on_submit():
        kelu = admindb(username=form.username.data, email=form.email.data, password=form.password.data)
        db.session.add(kelu)
        db.session.commit()
        return redirect(url_for("admingam.home"))
    return render_template("admin.html", form=form)

@admingam.route("/login_adm", methods=["GET","POST"])
def login_adm():
    form=LoginA()
    if form.validate_on_submit():
        cekmail = admindb.query.filter_by(email=form.email.data).first()
        if cekmail and (cekmail.password, form.password.data):
            login_user(cekmail)
            return redirect(url_for("admingam.admin_panel"))
        else:
            print("login salah harap periksa email dan password")
    return render_template("login.html", form=form)

@admingam.route('/logout_adm')
def logout_adm():
    logout_user()
    return redirect(url_for('admingam.home'))

@admingam.route("/tambahkat", methods=["GET","POST"])
@login_required
def tambah_kat():
    form = KategoriF()
    if form.validate_on_submit():
        nama = Kategori(nama=form.nama_kat.data)
        db.session.add(nama)
        db.session.commit()
        return redirect(url_for("admingam.admin_panel"))
    return render_template("kategori.html", form=form)
    
@admingam.route("/tambah_artikel", methods=["GET","POST"])
@login_required
def tambah_artikel():
  form=ArtikelP()
  form.kategori_id.choices = [(str(kategori_id.id), kategori_id.nama) for kategori_id in Kategori.query.all()]
  if form.validate_on_submit():
    random_hex = secrets.token_hex(8)
    gambar = form.thumbnail.data
    _, f_ext = os.path.splitext(gambar.filename)
    nama_gambar = random_hex + f_ext
    gambar.save(os.path.join(app.root_path, 'affairs/static/img', nama_gambar))
    artl = Artikel(judul=form.judul.data, konten=form.konten.data, thumbnail=nama_gambar ,kategori_id=form.kategori_id.data)
    db.session.add(artl)
    db.session.commit()
    return redirect(url_for('admingam.admin_panel'))
  #form.kategori_.choices.insert(0, ('','===pilih kategori==='))
  return render_template("Artikel.html",form=form, title='Tambah Berita')

@admingam.route('/admin_panel')
@login_required
def admin_panel():
    artl = Artikel.query.all()
    return render_template('admin_panel.html', artl=artl, title='Admin Panel')

@admingam.route('/edit_artikel/<int:id>', methods=["GET","POST"])
def edit_artikel(id):
    form=editArtikel()
    ed_a = Artikel.query.get_or_404(id)
    form.kategori_id.choices = [(str(kategori_id.id), kategori_id.nama) for kategori_id in Kategori.query.all()]
    if request.method == "GET":
        form.judul.data = ed_a.judul
        form.konten.data = ed_a.konten
        form.thumbnail.data = ed_a.thumbnail
        form.kategori_id.data = ed_a.kategori_id
    elif form.validate_on_submit():
        if form.thumbnail.data:
            foto = gthumbnail(form.thumbnail.data)
            ed_a.thumbnail = foto
        ed_a.judul = form.judul.data
        ed_a.konten = form.konten.data
        ed_a.kategori_id = form.kategori_id.data
        db.session.commit()
        return redirect(url_for('admingam.admin_panel'))
    return render_template("edit_artikel.html", form=form, title='Edit Berita')

@admingam.route("/hapus_ar/<int:id>",  methods=["POST"])
@login_required
def hapus_ar(id):
    art = Artikel.query.get_or_404(id)
    if request.method == "POST":
        db.session.delete(art)
        db.session.commit()
        return redirect(url_for('admingam.admin_panel'))
    return redirect(url_for('admingam.admin_panel'))

@admingam.route('/halamanrek-air', methods=["GET","POST"])
@login_required
def csvupload():
    halaman = request.args.get('page',1, type=int)
    Air = CustomerPgAir.query.order_by(CustomerPgAir.id.desc()).paginate(page=halaman, per_page=10)
    return render_template('hal_rek_air.html', Air=Air)

@admingam.route('/hapus-air/<int:id>')
def hapus_air(id):
    air = CustomerPgAir.query.get_or_404(id)
    if request.method == "POST":
        db.session.delete(air)
        db.session.commit()
        return redirect(url_for('admingam.csvupload'))
    return redirect(url_for('admingam.csvupload'))

@admingam.route("/displaycsv",  methods=["GET","POST"])
@login_required
def displaycsv():
    data = []
    form = UploadCSv()
    if form.validate_on_submit():
      fcsv = savecsv(form.csvField.data)
      cus = CustomerPgAir(csv_field=fcsv)
      db.session.add(cus)
      db.session.commit()
      return redirect(url_for('admingam.csvupload'))
    return render_template('displayfile.html', form=form, title="upload file")
    
@admingam.route('/lamanrek')
def lamanrek():
    halaman = request.args.get('page',1, type=int)
    rek = CustomerPgAir.query.order_by(CustomerPgAir.id.desc()).paginate(page=halaman, per_page=10)
    return render_template('lamanrek.html', rek=rek,title='Daftar Rekening Bulanan')
            
# @admingam.route('/hapusrek/<int:id>')
# # @login_required
# def hapusrek(id):
#     hps = CustomerPgAir.query.get_or_404(id)
#     db.session.delete(hps)
#     db.session.commit()
#     return redirect(url_for('admingam.home'))            

@admingam.route('/lihatrek/<int:id>')
def lihatrek(id):
    rek = CustomerPgAir.query.filter_by(id=id).all()

    return render_template('lihatrek.html', rek=rek, title="tabel daftar")  

affairs/templates/about.html
{% extends 'layout.html%}

{% block content %}
 <h2 class="text-center">Sebuah website</h2>
{% endblock content%}

affairs/templates/admin.html
{% extends 'layout.html' %}

{%block content %}
<div class="col-md-8" style="background-color: aquamarine; padding-bottom: 8%; margin-left:20%;">
    <form action="{{ url_for('admingam.admin')}}" method="POST">
        {{form.hidden_tag()}}
        <div class="form-group">
            {{form.username.label(class="form-control-label")}}
            {%if form.username.errors%}
                {{form.username(class="form-control is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{form.username(class="form-control")}}
            {% endif %}
        </div>

        <div class="form-group">
            {{form.email.label(class="form-control-label")}}
            {%if form.email.errors%}
                {{form.email(class="form-control is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{form.email(class="form-control")}}
            {% endif %}
        </div>

        <div class="form-group">
            {{form.password.label(class="form-control-label")}}
            {%if form.password.errors%}
                {{form.password(class="form-control is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{form.password(class="form-control")}}
            {% endif %}
        </div>

        <div class="form-group">
            {{form.konf_pass.label(class="form-control-label")}}
            {%if form.konf_pass.errors%}
                {{form.konf_pass(class="form-control is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.konf_pass.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{form.konf_pass(class="form-control")}}
            {% endif %}
        </div>
        
            {{form.submit(class="form-control btn btn-sm btn-dark")}}
        
    </form> 
</div>

{%endblock%}

affairs/templates/admin_panel.html
{% extends 'layout.html' %} 

{% block content %}

<div class="container">
    <div class="row">
        {% for ar in artl %}
        <div class="col-md-3">
            <div class="card">
                <img src="{{url_for('static', filename='img/' + ar.thumbnail)}}" alt="{{ar.judul}}" class="card-img-top">
                <div class="card-body"></div>
                <h5 class="card-title">{{ar.judul}}</h5>
                <p class="card-text">{{ar.konten | truncate(50)|striptags()}}</p>
                <div class="card-footer">
                    <a href="{{url_for('admingam.edit_artikel', id=ar.id)}}" class=" float-left btn btn-sm btn-primary">edit</a><button type="button" class="float-right btn btn-danger btn-sm" data-toggle="modal" data-target="#exampleModal-{{ar.id}}">
                      H
                    </button>
                    
                </div>
            </div>
        </div>
        <div class="modal fade" id="exampleModal-{{ar.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">{{ar.judul}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <span class="text-danger"> are you sure to delete this brand {{ar.judul}}</span>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
                <form action="{{url_for('admingam.hapus_ar', id=ar.id)}}" method="POST">
                  <button type="submit" class="btn btn-danger">Delete</button>
                </form>
                
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
        <hr>
    </div>
</div>
{% endblock content %}

affairs/templates/baca_ar.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">
    <h2 style="text-align: center;">{{bca.judul}}</h2>
    <h4>{{bca.ar.nama}}</h4>
    <p>{{bca.konten| safe}}</p>
</div>
{% endblock content %}

affairs/templates/contact.html
{% extends 'layout.html%}

{% block content %}
 <h1 class="text-center">No kontak: 085340987654</h1>
{% endblock content%}

affairs/templates/displayfile.html
{% extends 'layout.html' %}

{% block content %}

<div class="container" style="margin-top: 25%;">
    <form action="/displaycsv" method="POST" enctype="multipart/form-data">
        {{form.hidden_tag()}}

            <div class="form-group">

                
                {%if form.csvField.errors%}
                    {{form.csvField(class="form-control is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.csvField.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.csvField(class="form-control")}}
                {% endif %}
            </div>
            <div class="form-group">
              {{form.submit(class="btn btn-sm btn-success")}}
            </div>
    </form>
    
</div>

{% endblock content %}

affairs/templates/edit_artikel.html
{% extends 'layout.html' %}



{%block content%}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 mt-5">
        <div class="container">
            <h2 class="text-center">edit artikel</h2>
            <form action="" method="POST" enctype="multipart/form-data">
                {{form.hidden_tag()}}
                <div class="form-group">

                    {%if form.judul.errors%}
                        {{form.judul(class="form-control is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.judul.errors %}
                            <span>{{error}}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.judul(class="form-control")}}
                    {% endif %}
                </div>
                <div class="form-group">
                  {% if form.konten.errors %}
                      {{form.konten(class="form-control is-invalid")}}
                        {% for error in form.konten.errors %}
                          <div class="invalid-feedback">
                            {{error}}
                          </div>
                          {%endfor%}
                  {%else%}
                   {{form.konten.label()}}
                   {{form.konten(class="form-control")}}
                  {%endif%}
                </div>
                  <div class="form-group">
                  {% if form.kategori_id.errors %}
                      {{form.kategori_id(class="form-control is-invalid")}}
                        {% for error in form.kategori_id.errors %}
                          <div class="invalid-feedback">
                            {{error}}
                          </div>
                          {%endfor%}
                  {%else%}
                  {{form.kategori_id.label()}}

                   {{form.kategori_id(class="form-control")}}

                  {%endif%}
                </div>
              <div class="form-group">
                {% if form.thumbnail.errors %}

                {{form.thumbnail(class="form-control is-invalid")}}
                {% for error in form.thumbnail.errors %}
                  <div class="invalid-feedback">
                    {{error}}
                  </div>
                {%endfor%}
          {%else%}
              {{form.thumbnail.label()}}
              {{form.thumbnail(class="form-control")}}
          {%endif%}
        </div>

                {{form.submit(class="btn btn-sm btn-primary")}}
            </form>
        </div>
        </div>
    <div class="col-md-2"></div>
</div>
{{ ckeditor.load() }}
{{ ckeditor.config(name="konten") }}
{%endblock content%}

affairs/templates/hal_rek_air.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">
    <div class="row">
        {% for a in Air.items  %}
        <div class="col-md-3">
            <div class="card">
                <div class="card-body"></div>
                <h5 class="card-title"> Laporan Air bulan{{a.tgl_pst.strftime('%b, %Y')}}</h5>
                <p class="card-text"></p>
                <div class="card-footer">
                    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#exampleModal-{{a.id}}">
                      Hapus
                    </button>
                    
                </div>
            </div>
        </div>
        <div class="modal fade" id="exampleModal-{{a.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">{{a.tgl_pst.strftime('%b, %Y')}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <span class="text-danger"> ingin menghapus laporan rekening Air {{a.tgl_pst.strftime('%b, %Y')}}</span>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
                <form action="{{url_for('admingam.hapus_air', id=a.id)}}" method="POST">
                  <button type="submit" class="btn btn-danger">Delete</button>
                </form>
                
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
    </div>  
    <hr>
      <div class="row">
        <div class="col text-center p-2">
          {% if Air.has_prev %}
          <a href="{{url_for('admingam.csvupload', page=Air.prev_num)}}" class="btn btn-info btn-sm mt-3">previous</a>
          {% endif %}
          {% for page_num in Air.iter_pages() %}
          {% if page_num %}
          {% if Air.page == page_num %}
          <a href="{{url_for('admingam.csvupload', page=page_num)}}" class="btn btn-info btn-sm mt-3">{{page_num}}</a>
          {% else %}
          <a href="{{url_for('admingam.csvupload', page=page_num)}}" class="btn btn-outline-info btn-sm mt-3">{{page_num}}</a>
          {% endif %}
          {% else %}
          ... 
          {% endif %}
          {% endfor %}

          {% if Air.has_next %}
          <a href="{{url_for('admingam.csvupload', page=Air.next_num)}}" class="btn btn-info btn-sm mt-3">next</a>
          {% endif %}
        </div>
      </div>  
</div>
{% endblock content%}

affairs/templates/index.html
{% extends 'layout.html'%}
{%block content %}
<div class="row text-center" style="justify-content: center;">
{% for df in daf_ar.items %}
  
      <div class="card w-75 text-center mb-2">
        <div class="card-body">
          <h5 class="card-title">{{df.judul}}</h5>
          <hr>
          <p class="card-text">{{df.konten | truncate(200) | striptags}}</p>
          <a href="{{url_for('admingam.baca_ar', id=df.id)}}" class="btn btn-secondary btn-sm">baca selengkapnya</a>
        </div>
        <p class="text-muted ml-5">{{df.tgl_post.strftime('%B %d, %Y')}}</p>
      </div>
      <br>
  {% endfor %}
<br>
</div>
  </div>  
      <hr>
      <div class="row">
        <div class="col text-center p-2">
          {% if daf_ar.has_prev %}
          <a href="{{url_for('admingam.home', page=daf_ar.prev_num)}}" class="btn btn-info btn-sm mt-3">previous</a>
          {% endif %}
          {% for page_num in daf_ar.iter_pages() %}
          {% if page_num %}
          {% if daf_ar.page == page_num %}
          <a href="{{url_for('admingam.home', page=page_num)}}" class="btn btn-info btn-sm mt-3">{{page_num}}</a>
          {% else %}
          <a href="{{url_for('admingam.home', page=page_num)}}" class="btn btn-outline-info btn-sm mt-3">{{page_num}}</a>
          {% endif %}
          {% else %}
          ... 
          {% endif %}
          {% endfor %}

          {% if daf_ar.has_next %}
          <a href="{{url_for('admingam.home', page=daf_ar.next_num)}}" class="btn btn-info btn-sm mt-3">next</a>
          {% endif %}
        </div>
      </div>
{%endblock content %}

affairs/templates/kategori.html
{% extends 'layout.html' %}

{%block content%}
<div class="row">
    <div class="col-md-2" ></div>
    <div class="col-md-8 mt-5">
        <div class="container">
            <h2 class="text-center">tambah kategori</h2>
            <form action="/tambahkat" method="post">
                {{form.hidden_tag()}}
                <div class="form-group">

                    {%if form.nama_kat.errors%}
                        {{form.nama_kat(class="form-control is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.nama_kat.errors %}
                            <span>{{error}}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.nama_kat(class="form-control")}}
                    {% endif %}
                </div>
                {{form.submit(class="btn btn-sm btn-primary")}}
            </form>
        </div>
        </div>
    </div>
    <div class="col-md-2"></div>
</div>
{%endblock content%}

affairs/templates/lamanrek.html
{% extends'layout.html' %}

{% block content %}
{% for r in rek.items %}
<div class="row">
  <div class="card">
    <div class="card-body">
      <a href="{{url_for('admingam.lihatrek', id=r.id)}}">
        Laporan rekening air bulan {{r.tgl_pst.strftime('%b, %Y')}}
      </a>
    </div>
  </div>
</div>
{% endfor %}
<hr />
<div class="row">
  <div class="col text-center p-2">
    {% if rek.has_prev %}
    <a href="{{url_for('admingam.lamanrek', page=rek.prev_num)}}" class="btn btn-info btn-sm mt-3">previous</a>
    {% endif %}
    {% for page_num in rek.iter_pages() %}
    {% if page_num %}
    {% if rek.page == page_num %}
    <a href="{{url_for('admingam.lamanrek', page=page_num)}}" class="btn btn-info btn-sm mt-3">{{page_num}}</a>
    {% else %}
    <a href="{{url_for('admingam.lamanrek', page=page_num)}}" class="btn btn-outline-info btn-sm mt-3">{{page_num}}</a>
    {% endif %}
    {% else %}
    ... 
    {% endif %}
    {% endfor %}

    {% if rek.has_next %}
    <a href="{{url_for('admingam.lamanrek', page=rek.next_num)}}" class="btn btn-info btn-sm mt-3">next</a>
    {% endif %}
  </div>
</div>
{% endblock content  %}

affairs/templates/layout.html
<!doctype html>
<html lang="en">
  <head>
     <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Home</title>
  </head>
  <body>
  <div class="container" >
    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-primary mb-2">
<!--        <p class="navbar-brand" >AFA-AFA</p>-->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
              {% if current_user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link" href="{{url_for('admingam.home')}}">Home <span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               Menu
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{{url_for('admingam.tambah_kat')}}">Tambah Kategori</a>
                <a class="dropdown-item" href="{{url_for('admingam.tambah_artikel')}}">Tambah Berita atau Pengumuman</a>
                <a class="dropdown-item" href="{{url_for('admingam.admin_panel')}}">Admin Panel</a>
                <a class="dropdown-item" href="{{url_for('admingam.csvupload')}}">Panel Laporan Air</a>
                <a class="dropdown-item" href="{{url_for('admingam.displaycsv')}}">Upload Rekening Air</a>
                <a class="dropdown-item" href="{{url_for('admingam.logout_adm')}}">Logout</a>
              </div>
            </li>
            {%else %}
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('admingam.home')}}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('admingam.login_adm')}}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('admingam.lamanrek')}}">Pengumuman Air</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('admingam.about')}}">About</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
      {%block content%}
      {%endblock content%}

</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

affairs/templates/lihatrek.html
{% extends 'layout.html' %}

{% block content%}
<div class="container mt-5">
    <table class="display table responsive" style="width: 100%;">
    <thead>
      {% for r in rek %}  
      <tr>
        <th>No</th>
        <th>Nama</th>
        <th>Rt</th>
        <th>Harga</th>
        <th>Keterangan</th>
      </tr>
    </thead>
    <tbody>
        {% for i in r.csv_field  %}
       <tr>
           <td>{{loop.index}}</td>
           <td>{{i['Nama']}}</td>
           <td>{{i['Rt']}}</td>
           <td>{{i['Harga']|truncate(20)}}</td>
           <td>{{i['Keterangan']}}</td>
       </tr>
       {% endfor %}
    </tbody>
    {% endfor %}
    </table>
</div>
{% endblock content %}